version: '3'
services:
  ezbeq:
    image: ghcr.io/fattykidd/ezbeq:test
    network_mode: bridge
    volumes:
      - /path/to/your/config:/config
    ports:
      - 8080:8080
    restart: unless-stopped
